import { createClient } from '../docs/app/core/hardcover.js';
import { loadToken } from '../src/store.js';
const gql = createClient(await loadToken());
const d = await gql(`query { search(query:"dungeon crawler carl", query_type:"Book", per_page:1, page:1){ results } }`);
const doc = d.search.results.hits[0].document;
console.log('featured_series =', JSON.stringify(doc.featured_series));
console.log('featured_series_position =', JSON.stringify(doc.featured_series_position));
console.log('series_names =', JSON.stringify(doc.series_names));
console.log('image =', JSON.stringify(doc.image));
console.log('\nall document keys:\n ', Object.keys(doc).sort().join(', '));
